CREATE USER bst_user IDENTIFIED BY bst_password;
GRANT CONNECT, RESOURCE TO bst_user;
ALTER USER bst_user QUOTA UNLIMITED ON USERS;
CREATE TABLE BST (
    N NUMBER PRIMARY KEY,
    P NUMBER
);
INSERT INTO BST (N, P) VALUES (1, 2);
INSERT INTO BST (N, P) VALUES (3, 2);
INSERT INTO BST (N, P) VALUES (6, 8);
INSERT INTO BST (N, P) VALUES (9, 8);
INSERT INTO BST (N, P) VALUES (2, 5);
INSERT INTO BST (N, P) VALUES (8, 5);
INSERT INTO BST (N, P) VALUES (5, NULL);

COMMIT;
SELECT N,
       CASE 
           WHEN P IS NULL THEN 'Root'
           WHEN N NOT IN (SELECT DISTINCT P FROM BST WHERE P IS NOT NULL) THEN 'Leaf'
           ELSE 'Inner'
       END AS NodeType
FROM BST
ORDER BY N;
